// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package room

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/hekigan/couples/internal/services"

// RequestAccepted renders the updated guest info and UI changes when request is accepted
func RequestAccepted(data *services.RequestAcceptedData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<span class=\"player-label\">Guest</span> <span class=\"player-name\" id=\"guest-name\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(data.GuestUsername)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/fragments/room/request_accepted.templ`, Line: 8, Col: 63}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</span><script>\n\t\t// Update UI when guest joins\n\t\t(function() {\n\t\t\t// Show categories section\n\t\t\tconst categoriesSection = document.getElementById('categories-section');\n\t\t\tif (categoriesSection) {\n\t\t\t\tcategoriesSection.style.display = '';\n\t\t\t}\n\n\t\t\t// Show start game section (owner only)\n\t\t\tconst startGameSection = document.getElementById('start-game-section');\n\t\t\tif (startGameSection) {\n\t\t\t\tstartGameSection.style.display = '';\n\t\t\t}\n\n\t\t\t// Hide invite friends section\n\t\t\tconst inviteSection = document.getElementById('invite-section');\n\t\t\tif (inviteSection) {\n\t\t\t\tinviteSection.style.display = 'none';\n\t\t\t}\n\n\t\t\t// Hide join requests section\n\t\t\tconst joinRequestsSection = document.getElementById('join-requests-section');\n\t\t\tif (joinRequestsSection) {\n\t\t\t\tjoinRequestsSection.style.display = 'none';\n\t\t\t}\n\n\t\t\t// Remove 'empty' class from guest card\n\t\t\tconst guestCard = document.getElementById('guest-info');\n\t\t\tif (guestCard) {\n\t\t\t\tguestCard.classList.remove('empty');\n\t\t\t}\n\n\t\t\tconsole.log('✅ Guest joined - UI updated');\n\t\t})();\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
