// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package admin

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/hekigan/couples/internal/services"
	"github.com/hekigan/couples/internal/viewmodels"
	adminFragments "github.com/hekigan/couples/internal/views/fragments/admin"
	"github.com/hekigan/couples/internal/views/layouts"
)

// QuestionsPage renders the admin questions page with layout
func QuestionsPage(templateData *viewmodels.TemplateData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = layouts.Admin(templateData, QuestionsContent(templateData)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// QuestionsContent renders the admin questions management content
func QuestionsContent(templateData *viewmodels.TemplateData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"admin-container\"><h1>Question Management</h1><div class=\"admin-actions-header\"><div class=\"admin-filters-bar\"><a href=\"/admin/api/questions/export-csv\" class=\"btn\">Export CSV</a> <a href=\"/admin/api/questions/template-csv\" class=\"btn\">Download Template</a></div><button data-target=\"create-modal\" onclick=\"toggleModal(event)\" class=\"btn-add\">Add Question</button></div><div class=\"admin-table\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data, ok := templateData.Data.(*services.QuestionsListData); ok {
			templ_7745c5c3_Err = adminFragments.QuestionsList(data).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<p>No questions found.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div><!-- Create Question Modal - Using PicoCSS dialog element --><dialog id=\"create-modal\" class=\"modal-wide\"><article><header><button aria-label=\"Close\" rel=\"prev\" data-target=\"create-modal\" onclick=\"toggleModal(event)\"></button><h3>Create Question</h3></header><div id=\"create-modal-content\" class=\"modal-content\" hx-get=\"/admin/api/v1/questions/new\" hx-trigger=\"load once\"><!-- Form will be loaded here via HTMX --></div><footer><button type=\"button\" class=\"secondary\" data-target=\"create-modal\" onclick=\"toggleModal(event)\">Cancel</button> <button type=\"button\" class=\"success\" onclick=\"submitModalForm(event)\">Create</button></footer></article></dialog><!-- Edit Question Modal --><dialog id=\"edit-modal\" class=\"modal-wide\"><article><header><button aria-label=\"Close\" rel=\"prev\" data-target=\"edit-modal\" onclick=\"toggleModal(event)\"></button><h3>Edit Question</h3></header><div id=\"edit-modal-content\" class=\"modal-content\"><!-- Form will be loaded here via HTMX --></div><footer><button type=\"button\" class=\"secondary\" data-target=\"edit-modal\" onclick=\"toggleModal(event)\">Cancel</button> <button type=\"button\" class=\"success\" onclick=\"submitModalForm(event)\">Save</button></footer></article></dialog>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
