// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package auth

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/hekigan/couples/internal/viewmodels"
	"github.com/hekigan/couples/internal/views/layouts"
)

// LoginPage renders the login page with layout
func LoginPage(data *viewmodels.TemplateData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = layouts.Base(data, LoginContent(data)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// LoginContent renders the login form
func LoginContent(data *viewmodels.TemplateData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"auth-container\"><div class=\"auth-card\"><h1>Login</h1><div class=\"auth-options\"><section><a href=\"/auth/oauth/google\" role=\"button\" class=\"btn-oauth btn-google\"><span>Continue with Google</span></a> <a href=\"/auth/oauth/facebook\" role=\"button\" class=\"btn-oauth btn-facebook\"><span>Continue with Facebook</span></a></section><section class=\"divider\"><span>OR</span></section><section><form hx-post=\"/login\" hx-swap=\"none\" hx-disabled-elt=\"button[type='submit']\" hx-indicator=\"#login-loading\" hx-on::after-request=\"handleLoginResponse(event)\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.CSRFToken != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<input type=\"hidden\" name=\"csrf\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(data.CSRFToken)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/pages/auth/login.templ`, Line: 39, Col: 62}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<input type=\"email\" name=\"email\" placeholder=\"Email\" required autocomplete=\"email\" aria-label=\"Email address\"> <input type=\"password\" name=\"password\" placeholder=\"Password\" required autocomplete=\"current-password\" aria-label=\"Password\"> <button type=\"submit\" class=\"secondary\"><span id=\"login-loading\" class=\"htmx-indicator\" style=\"display:none;\">⏳ </span> Login</button></form><p class=\"help-text\" style=\"text-align: center; margin-top: 1rem;\">Don't have an account? <a href=\"/signup\" style=\"color: var(--primary);\">Sign up</a></p></section></div></div></div><script>\n\t\tfunction handleLoginResponse(event) {\n\t\t\tconst xhr = event.detail.xhr;\n\n\t\t\tif (xhr.status === 200) {\n\t\t\t\t// Success - HTMX handles HX-Redirect automatically\n\t\t\t\tToast.success('Login successful! Redirecting...');\n\t\t\t} else {\n\t\t\t\t// Error - parse JSON and show toast\n\t\t\t\ttry {\n\t\t\t\t\tconst response = JSON.parse(xhr.responseText);\n\t\t\t\t\tToast.error(response.error || 'Login failed. Please try again.');\n\t\t\t\t} catch (e) {\n\t\t\t\t\tToast.error('Login failed. Please check your credentials.');\n\t\t\t\t}\n\n\t\t\t\t// Clear password field on error\n\t\t\t\tevent.target.querySelector('input[name=\"password\"]').value = '';\n\t\t\t}\n\t\t}\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
