// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package auth

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/hekigan/couples/internal/viewmodels"
	"github.com/hekigan/couples/internal/views/layouts"
)

// OAuthCallbackPage renders the OAuth callback page with layout
func OAuthCallbackPage(data *viewmodels.TemplateData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = layouts.Base(data, OAuthCallbackContent()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// OAuthCallbackContent renders the OAuth callback content
func OAuthCallbackContent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"auth-callback-container\"><article class=\"auth-callback-card\"><header><h2>Completing Login...</h2></header><div class=\"loading-spinner\"><div class=\"spinner\"></div></div><p>Please wait while we complete your authentication.</p></article></div><script>\n\t\t(function() {\n\t\t\t// Extract tokens from URL fragment\n\t\t\tconst hash = window.location.hash.substring(1);\n\t\t\tconst params = new URLSearchParams(hash);\n\n\t\t\tconst accessToken = params.get('access_token');\n\t\t\tconst refreshToken = params.get('refresh_token');\n\t\t\tconst error = params.get('error');\n\t\t\tconst errorDescription = params.get('error_description');\n\n\t\t\tif (error) {\n\t\t\t\talert('Authentication error: ' + (errorDescription || error));\n\t\t\t\twindow.location.href = '/login';\n\t\t\t\treturn;\n\t\t\t}\n\n\t\t\tif (accessToken) {\n\t\t\t\t// Send tokens to server\n\t\t\t\tfetch('/auth/oauth/token', {\n\t\t\t\t\tmethod: 'POST',\n\t\t\t\t\theaders: {\n\t\t\t\t\t\t'Content-Type': 'application/json',\n\t\t\t\t\t},\n\t\t\t\t\tbody: JSON.stringify({\n\t\t\t\t\t\taccess_token: accessToken,\n\t\t\t\t\t\trefresh_token: refreshToken\n\t\t\t\t\t})\n\t\t\t\t})\n\t\t\t\t.then(response => {\n\t\t\t\t\tif (response.ok) {\n\t\t\t\t\t\twindow.location.href = '/';\n\t\t\t\t\t} else {\n\t\t\t\t\t\tthrow new Error('Failed to process authentication');\n\t\t\t\t\t}\n\t\t\t\t})\n\t\t\t\t.catch(error => {\n\t\t\t\t\tconsole.error('Error:', error);\n\t\t\t\t\talert('Failed to complete authentication. Please try again.');\n\t\t\t\t\twindow.location.href = '/login';\n\t\t\t\t});\n\t\t\t} else {\n\t\t\t\t// No token in fragment, might be PKCE flow with query params\n\t\t\t\t// Redirect to let server handle it\n\t\t\t\twindow.location.href = window.location.pathname + window.location.search;\n\t\t\t}\n\t\t})();\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
