// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"github.com/hekigan/couples/internal/models"
	"github.com/hekigan/couples/internal/viewmodels"
	"reflect"
	"time"
)

// formatNotificationCount formats the notification count as a string, showing 99+ for counts > 99
func formatNotificationCount(count int) string {
	if count > 99 {
		return "99+"
	}
	return fmt.Sprintf("%d", count)
}

// getNotificationIcon returns the icon class for a notification type
func getNotificationIcon(notifType string) string {
	icons := map[string]string{
		models.NotificationTypeRoomInvite:     "icon-join-room",
		models.NotificationTypeFriendRequest:  "icon-people_alt",
		models.NotificationTypeFriendAccepted: "icon-sentiment_very_satisfied",
		models.NotificationTypeGameStart:      "icon-sports_esports",
		models.NotificationTypeMessage:        "icon-comments",
	}
	if icon, ok := icons[notifType]; ok {
		return icon
	}
	return "icon-notifications"
}

// formatNotificationTime formats a timestamp into a relative time string
func formatNotificationTime(t time.Time) string {
	now := time.Now()
	diff := now.Sub(t)

	if diff < time.Minute {
		return "Just now"
	}
	if diff < time.Hour {
		mins := int(diff.Minutes())
		return fmt.Sprintf("%dm ago", mins)
	}
	if diff < 24*time.Hour {
		hours := int(diff.Hours())
		return fmt.Sprintf("%dh ago", hours)
	}
	if diff < 7*24*time.Hour {
		days := int(diff.Hours() / 24)
		return fmt.Sprintf("%dd ago", days)
	}
	return t.Format("Jan 2")
}

// AggregatedNotification represents notifications grouped by type
type AggregatedNotification struct {
	Type      string
	Count     int
	Icon      string
	Label     string
	HasUnread bool
	Link      string
}

// aggregateNotifications groups notifications by type
func aggregateNotifications(notifications []*models.Notification) []AggregatedNotification {
	typeMap := make(map[string]*AggregatedNotification)

	typeLabels := map[string]string{
		models.NotificationTypeRoomInvite:     "Room invitation",
		models.NotificationTypeFriendRequest:  "Friend request",
		models.NotificationTypeFriendAccepted: "Friend accepted",
		models.NotificationTypeGameStart:      "Game started",
		models.NotificationTypeMessage:        "Message",
	}

	typeLinks := map[string]string{
		models.NotificationTypeRoomInvite:     "/game/rooms",
		models.NotificationTypeFriendRequest:  "/friends",
		models.NotificationTypeFriendAccepted: "/friends",
		models.NotificationTypeGameStart:      "/game/rooms",
		models.NotificationTypeMessage:        "/",
	}

	for _, notif := range notifications {
		if agg, exists := typeMap[notif.Type]; exists {
			agg.Count++
			if !notif.Read {
				agg.HasUnread = true
			}
		} else {
			label := typeLabels[notif.Type]
			if label == "" {
				label = "Notification"
			}
			link := typeLinks[notif.Type]
			if link == "" {
				link = "/"
			}

			typeMap[notif.Type] = &AggregatedNotification{
				Type:      notif.Type,
				Count:     1,
				Icon:      getNotificationIcon(notif.Type),
				Label:     label,
				HasUnread: !notif.Read,
				Link:      link,
			}
		}
	}

	// Convert map to slice
	result := make([]AggregatedNotification, 0, len(typeMap))
	for _, agg := range typeMap {
		result = append(result, *agg)
	}

	return result
}

// pluralizeLabel adds (s) if count > 1
func pluralizeLabel(label string, count int) string {
	if count > 1 {
		return label + "(s)"
	}
	return label
}

// filterUnreadNotifications returns only unread notifications
func filterUnreadNotifications(notifications []*models.Notification) []*models.Notification {
	var unread []*models.Notification
	for _, n := range notifications {
		if !n.Read {
			unread = append(unread, n)
		}
	}
	return unread
}

// NotificationBadgeContent renders just the badge (for HTMX updates)
func NotificationBadgeContent(count int) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if count > 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<span id=\"notification-badge\" class=\"notification-badge visible\" hx-get=\"/api/v1/notifications/badge\" hx-trigger=\"refreshNotificationBadge from:body\" hx-swap=\"outerHTML\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(formatNotificationCount(count))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/layouts/header.templ`, Line: 146, Col: 35}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<span id=\"notification-badge\" class=\"notification-badge\" hidden hx-get=\"/api/v1/notifications/badge\" hx-trigger=\"refreshNotificationBadge from:body\" hx-swap=\"outerHTML\">0</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

// NotificationListContent renders just the notification list content (for HTMX updates)
func NotificationListContent(notifications []*models.Notification) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if len(filterUnreadNotifications(notifications)) == 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"empty\">No new notifications</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			for _, agg := range aggregateNotifications(filterUnreadNotifications(notifications)) {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<a href=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 templ.SafeURL
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinURLErrs(templ.URL(agg.Link))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/layouts/header.templ`, Line: 162, Col: 30}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" class=\"notification-item unread\"><div class=\"notification-icon\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var5 = []any{agg.Icon}
				templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var5...)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<i class=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var6 string
				templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var5).String())
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/layouts/header.templ`, Line: 1, Col: 0}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\"></i></div><div class=\"notification-content\"><div class=\"notification-title\"><span class=\"notification-count-badge\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var7 string
				templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", agg.Count))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/layouts/header.templ`, Line: 170, Col: 75}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</span> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var8 string
				templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(pluralizeLabel(agg.Label, agg.Count))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/layouts/header.templ`, Line: 171, Col: 44}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</div></div><div class=\"unread-dot\"></div></a>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
		}
		return nil
	})
}

// getUserIDForHeader extracts the user ID from the User interface using reflection
func getUserIDForHeader(user interface{}) string {
	if user == nil {
		return ""
	}

	v := reflect.ValueOf(user)

	// If it's a pointer, get the element it points to
	if v.Kind() == reflect.Ptr {
		if v.IsNil() {
			return ""
		}
		v = v.Elem()
	}

	// If it's a struct, try to get the ID field
	if v.Kind() == reflect.Struct {
		idField := v.FieldByName("ID")
		if !idField.IsValid() {
			return ""
		}

		// Handle string ID (SessionUser)
		if idField.Kind() == reflect.String {
			return idField.String()
		}

		// Handle uuid.UUID type (models.User) - UUID has a String() method
		if idField.Type().Name() == "UUID" {
			// Call the String() method on uuid.UUID
			stringMethod := idField.MethodByName("String")
			if stringMethod.IsValid() {
				result := stringMethod.Call(nil)
				if len(result) > 0 {
					return result[0].String()
				}
			}
		}
	}

	return ""
}

// Header renders the main header navigation
func Header(data *viewmodels.TemplateData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var9 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var9 == nil {
			templ_7745c5c3_Var9 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<header class=\"main-header\"><div class=\"container\"><div class=\"header-content\"><a href=\"/\" class=\"logo\"><span class=\"logo-icon\">💕</span> <span class=\"logo-text\">Couple Card Game</span></a> <button class=\"hamburger-btn\" onclick=\"MobileMenu.open()\" aria-label=\"Open menu\"><span class=\"hamburger-icon\">☰</span></button><nav class=\"main-nav\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.User != nil {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<!-- Notification Bell --> <span role=\"button\" class=\"notification-bell nav-link\" id=\"notification-btn\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if getUserIDForHeader(data.User) != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, " data-user-id=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var10 string
				templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(getUserIDForHeader(data.User))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/layouts/header.templ`, Line: 244, Col: 52}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "><i class=\"icon-email text-lg\"></i>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = NotificationBadgeContent(data.NotificationCount).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "<div class=\"notification-dropdown\" id=\"notification-dropdown\"><div class=\"notification-header\"><button class=\"mark-read-btn\" hx-post=\"/api/v1/notifications/mark-all-read\" hx-target=\"#notification-list\" hx-swap=\"innerHTML\">Mark all read</button></div><div class=\"notification-list\" id=\"notification-list\" data-loaded=\"true\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = NotificationListContent(data.Notifications).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "</div></div></span> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if data.IsAdmin {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "<a href=\"/admin\" role=\"button\" class=\"nav-link\">Admin Dashboard</a>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, " <a href=\"/friends\" role=\"button\" class=\"nav-link\">Friends</a> <a href=\"/game/rooms\" role=\"button\" class=\"nav-link\">Rooms</a> <a href=\"/profile\" role=\"button\" class=\"nav-link\">Profile</a> <a href=\"#\" role=\"button\" hx-post=\"/auth/logout\" hx-confirm=\"Are you sure you want to logout?\" class=\"nav-link\">Logout</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "<a href=\"/login\" role=\"button\">Login</a> <a href=\"/signup\" role=\"button\">Signup</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "</nav></div></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
