// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/hekigan/couples/internal/viewmodels"

// MobileMenu renders the mobile navigation menu
func MobileMenu(data *viewmodels.TemplateData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- Mobile Menu --><div class=\"mobile-menu-overlay\" id=\"mobile-menu-overlay\" data-menu=\"close\"></div><div class=\"mobile-menu-panel\" id=\"mobile-menu-panel\" data-menu=\"close\"><div class=\"mobile-menu-header\"><h2 class=\"menu-title\">Menu</h2><button class=\"close-btn\" id=\"mobile-menu-close\" aria-label=\"Close menu\">×</button></div><nav class=\"mobile-menu-nav\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.User != nil {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<a href=\"#\" class=\"notification-bell\" onclick=\"toggleNotifications()\" id=\"notification-btn-mobile\">📧 <span class=\"notification-badge\" id=\"notification-badge-mobile\" hidden>0</span></a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if data.IsAdmin {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<a href=\"/admin\" class=\"nav-link\">Admin Dashboard</a>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " <a href=\"/friends\" class=\"nav-link\">Friends</a> <a href=\"/game/rooms\" class=\"nav-link\">Rooms</a> <a href=\"/profile\" class=\"nav-link\">Profile</a> <a href=\"#\" hx-post=\"/auth/logout\" hx-confirm=\"Are you sure you want to logout?\" class=\"nav-link\">Logout</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<a href=\"/login\" role=\"button\" class=\"success\">Login</a> <a href=\"/signup\" role=\"button\" class=\"success\">Signup</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</nav></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
